### ISSUE TITLE
Casting causes the app to go blank

### ISSUE THREAD

**Issue by paranerd** [ente/ente#5909]
### Description

I just installed the Ente Android app (v1.0.10) and tried casting an Album to my TV. With both the built-in Chromecast as well as a dedicated "Chromecast with Google TV" here's what happened:

1. Select an Album
2. Click on the "Cast" icon
3. Select Automatic connection
4. TV and Chromecast show up (sometimes took a second round for the app to find them)
5. TV shows pairing key
6. TV shows random image from the album
7. App goes blank

I then have to force-quit the app to use it again - which of course terminates the cast connection.

Am I missing something? Is anyone else having this issue?

### Version

1.0.10

### Last working version

-

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by casiopopasio** [comment]
I am experiencing the same behaviour on Android 16 on a Google Pixel 8. You can keep the black App open and the slideshow continues. But the only way to proceed is to force close the app.

**Comment by mo-st** [comment]
I have the same issue on the same software and hardware as casiopopasio

**Comment by dr3st** [comment]
I am getting the same issue, but I was able to test "casting" with PC / browser.
In my setup I use a local instance, server configured:

```
apps:
  public-albums: "https://albums.x.local.com"
  cast: "https://ente-cast.x.local.com"
  embed: "https://ente-embed.x.local.com"
```
So the server is reporting the URLs to clients, while traefik is reverse proxying:

```
    ente_albums:
      entrypoints: websecure
      rule: Host(`ente.x.local.com`)
      service: ente_albums
      tls: true
    ente_api:
      entrypoints: websecure
      rule: Host(`albums.x.local.com`)
      service: ente_api
      tls: true
    ente_cast:
      entrypoints: websecure
      rule: Host(`ente-cast.x.local.com`)
      service: ente_cast
      tls: true
    ente_embed:
      entrypoints: websecure
      rule: Host(`ente-embed.x.local.com`)
      service: ente_cast
      tls: true
services:
    ente_albums:
      loadbalancer:
        servers:
        - url: http://100.100.0.21:3002
    ente_api:
      loadbalancer:
        servers:
        - url: http://100.100.0.21:8080
    ente_cast:
      loadbalancer:
        servers:
        - url: http://100.100.0.21:3004
    ente_embed:
      loadbalancer:
        servers:
        - url: http://100.100.0.21:3006
    ente_web:
      loadbalancer:
        servers:
        - url: http://100.100.0.21:3000
```

After browsing to cast.x.local.com there was the expected (chrome)cast site with pairing-code. The code was generated and stored into database:
```
SELECT * FROM casting;
```

When using the desktop & mobile app, I may connect via PIN. Chromecast feature (testing with android TV) results into black app. But in general the casting feature is working :)
Hope this may help in any way.
